/*
	
	Copyright (c) 2013, Latitude Geographics Group Ltd.
	All rights reserved.
	       
	Redistribution is not permitted. 
	
	Use in binary form, without modification, is permitted provided that neither 
	the name of the organization nor the names of its contributors may be used 
	to endorse or promote products derived from this software without specific 
	prior written permission.
	       
	THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER ''AS IS'' AND ANY
	EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
	DISCLAIMED. IN NO EVENT SHALL LATITUDE GEOGRAPHICS GROUP LTD. BE LIABLE FOR ANY
	DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
	(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
	ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
	(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

geocortex||(geocortex={});if(!geocortex.essentialsHtmlViewer)geocortex.essentialsHtmlViewer={};geocortex.essentialsHtmlViewer.version="1.3.1.0045";var __extends=this.__extends||function(e,f){function k(){this.constructor=e}for(var i in f)f.hasOwnProperty(i)&&(e[i]=f[i]);k.prototype=f.prototype;e.prototype=new k},geocortex;
(function(e){(function(f){(function(k){var f=function(){return function(c,b,a){this.pageNumber=new Observable(c||null);this.isActive=new Observable(b||false);this.cssClass=new Observable(a||"pc-page-shortcut")}}();k.PresentableCollectionPageShortcut=f;var j=function(c){function b(a){c.call(this,null,null);this.filterPredicate=this.sortingPredicate=this.sortMethod=null;this.items=new ObservableCollection([]);this._itemCollection=new ObservableCollection([]);this.isSorted=new Observable(false);this.isFiltered=
new Observable(false);this.isPaginated=new Observable(true);this.isMultiplePages=new Observable(true);this.pageShortcuts=new ObservableCollection;this.numPageShortcuts=new Observable(10);this.numberOfItems=new Observable(0);this.currIndexStart=new Observable(0);this.currIndexStartFromOne=new Observable(1);this.currIndexEnd=new Observable(0);this.currPageNumber=new Observable(1);this.prevPageNumber=new Observable(null);this.nextPageNumber=new Observable(null);this.firstPageNumber=new Observable(1);
this.lastPageNumber=new Observable(1);this.pageSize=new Observable(5);this._prevIndexStart=this.currIndexStart.get();this._prevIndexEnd=this.currIndexEnd.get();this._prevPageNum=0;this._prevPageSize=this.pageSize.get();this.sortMethod=this.defaultNativeSort;this.sortingPredicate=function(a,b){return a===b?0:a>b?1:-1};a&&this.attachToCollection(a);this.auto(this.isSorted,this,function(a){a?this.sortCollection():this.unsortCollection()});this.currIndexStartFromOne.syncTransform(this.currIndexStart,
function(a){return a+1});this.auto(this.isPaginated,this,this._enableOrDisablePagination);this.auto(this.currPageNumber,this,this._handlePageChange);this.auto(this.pageSize,this,this._handlePageChange)}__extends(b,c);b.prototype.nextPage=function(){this.currPageNumber.set(this.currPageNumber.get()+1)};b.prototype.prevPage=function(){this.currPageNumber.set(this.currPageNumber.get()-1)};b.prototype.getAt=function(a){return this._itemCollection.getAt(a)};b.prototype.getLength=function(){return this._itemCollection.getLength()};
b.prototype.destroy=function(){c.prototype.destroy.call(this);this.cleanUp()};b.prototype.cleanUp=function(){this._itemCollection&&this._itemCollection.clear();this.items&&this.items.clear();if(this._underlyingCollection)this._underlyingCollection.unbind(this._underlyingCollectionBindingToken),this._underlyingCollectionBindingToken=this._underlyingCollection=null};b.prototype.attachToCollection=function(a){this.cleanUp();if(!a)throw Error("Could not attach to collection.");this._attachToUnderlyingCollection(a)};
b.prototype._attachToUnderlyingCollection=function(a){this._underlyingCollection=a;this._underlyingCollectionBindingToken=this._underlyingCollection.bind(this,this._handleUnderlyingCollectionChanges);this._itemCollection.set(a.getRange(0));a=this._itemCollection.getLength();this.numberOfItems.set(a);this.currIndexStart.set(0);this.currIndexEnd.set(this.pageSize.get());this.currPageNumber.set(1);if(a<this.currIndexEnd.get())this.currIndexEnd.set(a),this._prevIndexEnd=a;this._bindEntirePage();this._maintainPageRanges()};
b.prototype._bindEntirePage=function(){this._calculatePageWindow();this.items.clear();for(var a=[],d=this.currIndexStart.get(),b=this.currIndexEnd.get(),h=d;h<b;++h){var c=this._itemCollection.getAt(h);a.push(c)}this.items.addItems(a);this._prevIndexStart=d;this._prevIndexEnd=this._prevIndexEnd};b.prototype._enableOrDisablePagination=function(a){a?(this.currIndexStart.set(this.currPageNumber.get()*this._prevPageSize),this.pageSize.set(this._prevPageSize),this._calculatePageWindow(),this._bindEntirePage(),
this._maintainPageRanges()):(this.currIndexStart.set(0),this._prevPageSize=this.pageSize.get(),this.pageSize.set(Number.MAX_VALUE),this.pageShortcuts.clear(),this._calculatePageWindow(),this._bindEntirePage())};b.prototype._calculatePageWindow=function(){var a=this._itemCollection.length();this.lastPageNumber.set(Math.ceil(a/this.pageSize.get()));var d=this.currIndexStart.get(),b=this.currIndexEnd.get(),h=this.pageSize.get(),c=0,e=0,f=0;b>a&&(b=a);this.currIndexStart.set(0>d?0:d);this.currIndexEnd.set(Math.min(this._itemCollection.getLength(),
this.currIndexEnd.get()));c=this.currIndexStart.get()-this._prevIndexStart;a<=d&&(e=0,f=~~((d-a+1)/h+1),f*=-1,c=Math.max(0,f*h));b-d<h&&a>=b&&(e=Math.min(h,a)-(b-d));f!==0&&(c=0,e=0);return{pageShift:f,startShift:c,endShift:e}};b.prototype._handlePageChange=function(a){if(this.isPaginated.get()){if(this.pageSize.value=Math.max(0,Number(this.pageSize.get())),this.currPageNumber.value=Math.max(1,Number(this.currPageNumber.get())),!(isNaN(this.pageSize.get())||this.pageSize.get()<1))this.currPageNumber.get()>
this.lastPageNumber.get()&&this.lastPageNumber.get()>0?this.currPageNumber.set(this.lastPageNumber.get()):(this.currIndexStart.set((this.currPageNumber.get()-1)*this.pageSize.get()),this.currIndexEnd.set(Math.min(this._itemCollection.getLength(),this.currIndexStart.get()+this.pageSize.get())),this._prevIndexStart=this.currIndexStart.get(),this._prevIndexEnd=this.currIndexEnd.get(),this._maintainPageRanges(),this._bindEntirePage())}else if(a!=Number.MAX_VALUE)this._prevPageSize=a,this.pageSize.set(Number.MAX_VALUE)};
b.prototype._maintainPageRanges=function(){var a=Math.ceil(this._itemCollection.getLength()/this.pageSize.get());this.lastPageNumber.set(a);a>1&&!this.isMultiplePages.get()?this.isMultiplePages.set(true):a<=1&&this.isMultiplePages.get()&&this.isMultiplePages.set(false);this.firstPageNumber.set(1);var d=this.numPageShortcuts.get(),b=Math.max(0,this.currPageNumber.get()-d/2),h=d/2-(this.currPageNumber.get()-b),a=Math.min(a,this.currPageNumber.get()+d/2+h);a-b<this.numPageShortcuts.get()&&(b-=this.numPageShortcuts.get()-
(a-b),b<0&&(b=0));this.pageShortcuts.clear();for(d=[];b<a;++b)d.push(new f(b+1,false));this.pageShortcuts.addItems(d);this._highlightCorrectPageShortcut()};b.prototype._highlightCorrectPageShortcut=function(){for(var a=0;a<this.pageShortcuts.getLength();++a){var d=this.pageShortcuts.getAt(a);d.pageNumber.get()===this.currPageNumber.get()?d.cssClass.set("pc-page-shortcut pc-shortcut-active"):d.cssClass.set("pc-page-shortcut")}};b.prototype._performWindowRecalc=function(a){if(a.pageShift!==0)this.currIndexStart.set((this.currPageNumber.get()-
1)*this.pageSize.get()),this.currIndexEnd.set(this.currIndexStart.get()+this.pageSize.get()),this.currIndexStart.set(Math.max(0,this.currIndexStart.get())),this.currIndexEnd.set(Math.min(this._itemCollection.getLength(),this.currIndexEnd.get())),this._bindEntirePage();else{if(a.startShift<0){var d=this._itemCollection.getRange(Math.max(0,this._prevIndexStart+a.startShift),this._prevIndexStart-1);this.items.insertItems(0,d)}else a.startShift>0&&this.items.removeRange(0,a.startShift-1);a.endShift<0?
this.items.removeRange(this.items.getLength()+a.endShift,this.items.getLength()):a.endShift>0&&(d=Math.min(this._itemCollection.getLength(),this.currIndexEnd.get()+a.endShift),d=this._itemCollection.getRange(this.currIndexEnd.get(),d-1),this.items.addItems(d));this.currIndexStart.set(this.currIndexStart.get()+a.startShift);this.currIndexEnd.set(this.currIndexEnd.get()+a.endShift)}this._prevIndexStart=this.currIndexStart.get();this._prevIndexEnd=this.currIndexEnd.get()};b.prototype._handleUnderlyingCollectionChanges=
function(a){if(!a||a.type==="clear")this.items.clear(),this._itemCollection.clear(),this._calculatePageWindow();else if(a.type==="replace")this.items.clear(),this._itemCollection.clear(),this._itemCollection.addItems(this._underlyingCollection.getRange(0)),this._calculatePageWindow(),this._bindEntirePage();else if(a.type==="insert"){if(!this.isSorted.get()){var d=this._underlyingCollection.getRange(a.rangeStart,a.rangeEnd);this._itemCollection.insertItems(a.rangeStart,d);var g=b.getIntersectType(this.currIndexStart.get(),
this.currIndexEnd.get(),a.rangeStart,a.rangeEnd);g===b.RANGE_RELATION_BEFORE||g===b.RANGE_RELATION_HEAD?(a=a.rangeEnd-a.rangeStart+1,this._prevIndexStart+=a,this._prevIndexEnd+=a,this._performWindowRecalc({pageShift:0,startShift:-a,endShift:-a})):g===b.RANGE_RELATION_CONTAINED?(this._performWindowRecalc({pageShift:0,startShift:0,endShift:-(a.rangeEnd-a.rangeStart+1)}),this.items.insertItems(a.rangeStart-this.currIndexStart.get(),d)):g===b.RANGE_RELATION_TAIL?(this.items.removeRange(a.rangeStart-this.currIndexStart.get(),
this.items.getLength()),this.items.addItems(d.slice(this.pageSize.get()-(a.rangeEnd-a.rangeStart))),this._performWindowRecalc({pageShift:0,startShift:0,endShift:-(a.rangeEnd-a.rangeStart+1)})):g===b.RANGE_RELATION_AFTER?(a=this.currIndexEnd.get()-this.currIndexStart.get(),a<this.pageSize.get()&&this.items.addItems(d.slice(0,this.pageSize.get()-a))):this._bindEntirePage()}}else if(a.type==="append")if(this.isSorted.get())for(d=a.rangeStart;d<=a.rangeEnd;++d){var g=this._underlyingCollection.getAt(d),
h=this.getSortedPosition(g);this._itemCollection.insertItem(h,g);h<=this.currIndexStart.get()?(this.items.removeRange(this.items.getLength()-1),this.items.insertItem(0,this._itemCollection.getAt(this.currIndexStart.get()))):h>this.currIndexStart.get()&&h<=this.currIndexEnd.get()&&(this.items.removeRange(this.items.getLength()-1),this.items.insertItem(h-this.currIndexStart.get(),g))}else this._itemCollection.addItems(this._underlyingCollection.getRange(a.rangeStart,a.rangeEnd)),this._performWindowRecalc(this._calculatePageWindow());
else a.type==="remove"&&(a.rangeEnd-a.rangeStart>0?(this._itemCollection.removeRange(a.rangeStart,a.rangeEnd),this._bindEntirePage()):(d=-1,d=this.isSorted.get()?this.getSortedPosition(this._underlyingCollection.getAt(a.rangeStart)):a.rangeStart,this._itemCollection.removeRange(d,d),d<this.currIndexStart.get()?(this.currIndexEnd.set(this.currIndexEnd.get()-1),this._performWindowRecalc({pageShift:0,startShift:1,endShift:1}),this.currIndexEnd.set(this.currIndexEnd.get()+1)):d>=this.currIndexStart.get()&&
d<=this.currIndexEnd.get()&&(a=d-this.currIndexStart.get(),this.items.removeRange(a,a),this.currIndexEnd.set(this.currIndexEnd.get()-1),this._performWindowRecalc({pageShift:0,startShift:0,endShift:1}),this.currPageNumber.get()!==this.lastPageNumber.get()&&this.currIndexEnd.set(this.currIndexEnd.get()+1))));this.numberOfItems.set(this._itemCollection.getLength());this._maintainPageRanges()};b.prototype.sortCollection=function(){this.sortMethod(this._itemCollection.get(),this.sortingPredicate||null);
this._bindEntirePage()};b.prototype.unsortCollection=function(){this._itemCollection.set(this._underlyingCollection.getRange(0));this._bindEntirePage()};b.prototype.getSortedPosition=function(a){if(this.isSorted.get()===false)return this._itemCollection.getLength();var d=this._itemCollection.get();this._itemCollection.getLength();for(var b=0,h=d.length-1,c=~~((h-b)/2);c<h&&c>b;){var e=this.sortingPredicate(a,d[c]);if(this.sortingPredicate(a,d[h])===0)return h;if(this.sortingPredicate(a,d[b])===0)return b;
if(e>0)b=c;else if(e<0)h=c;else break;c=~~((h-b)/2)+b}return c};b.prototype.defaultNativeSort=function(a,b){var g=null;return g=b===null||typeof b==="undefined"?a.sort():a.sort(b)};b.getIntersectType=function(a,d,g,c){return a===g&&d===c?e.framework.ui.PresentableCollection.RANGE_RELATION_SAME:g<a&&c<=a?b.RANGE_RELATION_BEFORE:g<=a&&c<d?b.RANGE_RELATION_HEAD:g<a&&c>d?b.RANGE_RELATION_CONTAINS:g>a&&c<d?b.RANGE_RELATION_CONTAINED:g<=d&&c>=d?b.RANGE_RELATION_TAIL:g>d?b.RANGE_RELATION_AFTER:b.RANGE_RELATION_SAME};
b.RANGE_RELATION_SAME=0;b.RANGE_RELATION_BEFORE=1;b.RANGE_RELATION_HEAD=2;b.RANGE_RELATION_TAIL=3;b.RANGE_RELATION_AFTER=4;b.RANGE_RELATION_CONTAINS=5;b.RANGE_RELATION_CONTAINED=6;return b}(e.framework.FrameworkObject);k.PresentableCollection=j})(f.ui||(f.ui={}))})(e.framework||(e.framework={}))})(geocortex||(geocortex={}));
(function(e){(function(e){(function(e){(function(f){var j=function(c){function b(a,b){c.call(this,a,b);this._siteInitializedFailedToken=this._siteInitializedToken=null;this.app.commandRegistry.command("HideSplashScreen").register(this,function(){this.removeSplash()});this.app.site&&this.app.site.isInitialized?this.removeSplash():(this._siteInitializedToken=this.app.eventRegistry.event("SiteInitializedEvent").subscribe(this,function(){var a=this;setTimeout(function(){a.removeSplash()},0)}),this._siteInitializedFailedToken=
this.app.eventRegistry.event("SiteInitializationFailedEvent").subscribe(this,function(){var a=this;setTimeout(function(){a.removeSplash()},0)}),this._siteInitializedFailedToken=this.app.eventRegistry.event("UserSignInCancelledEvent").subscribe(this,function(){var a=this;setTimeout(function(){a.removeSplash()},0)}))}__extends(b,c);b.prototype.removeSplash=function(){this.app.viewManager.deactivateView(this);this.app.commandRegistry.command("HideSplashScreen").clear();this._siteInitializedToken&&this.app.eventRegistry.event("SiteInitializedEvent").unsubscribe(this._siteInitializedToken);
this._siteInitializedFailedToken&&this.app.eventRegistry.event("SiteInitializationFailedEvent").unsubscribe(this._siteInitializedFailedToken);var a=this;setTimeout(function(){a.app.viewManager.destroyView(a)},250)};return b}(e.ViewBase);f.SplashScreenView=j})(e.SplashScreen||(e.SplashScreen={}))})(e.ui||(e.ui={}))})(e.framework||(e.framework={}))})(geocortex||(geocortex={}));
(function(e){(function(f){(function(f){var i=function(f){function c(b){f.call(this);this._collectionsBindingToken=null;this._bindingTokens=[];b&&this.setCollectionsSource(b)}__extends(c,f);c.prototype.setCollectionsSource=function(b){if(b!==this._collections){if(this._collections!=null){this._collections.unbind(this._collectionsBindingToken);this._collectionsBindingToken=null;if(this._collections.length()>0){var a=new e.framework.events.CollectionChangedArgs;a.type="clear";a.rangeStart=0;a.rangeEnd=
this.length()-1;this.collectionsChanged(a)}this._collections=null}if(b!=null)this._collections=b,this._collectionsBindingToken=this._collections.bind(this,this.collectionsChanged),b=new e.framework.events.CollectionChangedArgs,b.rangeStart=0,b.rangeEnd=this._collections.length()-1,b.type="append",this.collectionsChanged(b)}};c.prototype.getCollectionSource=function(){return this._collections};c.prototype.collectionsChanged=function(b){this.fixBindings(b);this.propogateEvents(b)};c.prototype.fixBindings=
function(b){if(b.type=="append"||b.type=="insert")for(var a=b.rangeStart;a<=b.rangeEnd;a++)this._bindingTokens.splice(a,0,this._collections.getAt(a).bindingEvent.subscribe(this,this.underlyingCollectionChanged));else if(b.type=="remove"||b.type=="clear"){for(a=b.rangeStart;a<=b.rangeEnd;a++)this._collections.getAt(a).bindingEvent.unsubscribe(this._bindingTokens[a]),this._bindingTokens[a]=null;this._bindingTokens.splice(b.rangeStart,b.rangeEnd-b.rangeStart+1)}else if(b.type=="replace")throw Error("Uhoh the original value is lost and we need to unbind from it");
else throw Error("Unknown arg type");};c.prototype.propogateEvents=function(b){var a=this._collections.length(),d=new e.framework.events.CollectionChangedArgs;d.type=b.type;d.rangeStart=0;for(var g=d.rangeEnd=0;g<a&&g<b.rangeStart;g++)d.rangeStart+=this._collections.getAt(g).length();for(d.rangeEnd=d.rangeStart-1;g<a&&g<=b.rangeEnd;g++)d.rangeEnd+=this._collections.getAt(g).length();if(d.rangeEnd>=d.rangeStart)d.sender=this,this.bindingEvent.publish(d)};c.prototype.underlyingCollectionChanged=function(b){var a=
new e.framework.events.CollectionChangedArgs;a.sender=this;a.type=b.type;for(var d=0,g=this._collections.length(),c=0;c<g;c++){var f=this._collections.getAt(c);if(f===b.sender){if(b.type=="append"&&c!=g-1)a.type="insert";else if(b.type=="clear"&&g!=1)a.type="remove";a.rangeStart=d+b.rangeStart;a.rangeEnd=d+b.rangeEnd;break}else d+=f.length()}this.bindingEvent.publish(a)};c.prototype.isEmpty=function(){if(this._collections==null)return true;for(var b=this._collections.length(),a=0;a<b;a++)if(!this._collections.getAt(a).isEmpty())return false;
return true};c.prototype.length=function(){if(this._collections==null)return 0;for(var b=0,a=this._collections.length(),d=0;d<a;d++)b+=this._collections.getAt(d).length();return b};c.prototype.contains=function(b){if(this._collections==null)return false;for(var a=this._collections.length(),d=0;d<a;d++)if(this._collections.getAt(d).contains(b))return true;return false};c.prototype.getAt=function(b){if(this._collections==null)return null;for(var a=this._collections.length(),d=0;d<a;d++){var g=this._collections.getAt(d),
c=g.length();if(b>=c)b-=c;else return g.getAt(b)}throw Error("Index out of bounds");};c.prototype.getRange=function(b,a){if(this._collections==null)return[];if(a===void 0)a=Number.POSITIVE_INFINITY;for(var d=null,g=0,c=this._collections.length(),e=0;e<c&&a>=0;e++,b-=g,a-=g){var f=this._collections.getAt(e),g=f.length();g>b&&(f=f.getRange(b>0?b:0,a),d=d==null?f:d.concat(f))}return d};c.prototype.indexOf=function(b){if(this._collections==null)return-1;for(var a=0,d=this._collections.length(),g=0;g<
d;g++){var c=this._collections.getAt(g),e=c.indexOf(b);if(e!=-1)return length+e;a+=c.length()}return-1};c.prototype.get=function(){throw Error("Raw array manipulation not supported");};c.prototype.getItems=function(){throw Error("Raw array manipulation not supported");};c.prototype.getLength=function(){return this.length()};c.prototype.addItems=function(){throw Error("Operation not supported");};c.prototype.addItem=function(){throw Error("Operation not supported");};c.prototype.insertItems=function(){throw Error("Operation not supported");
};c.prototype.insertItem=function(){throw Error("Operation not supported");};c.prototype.removeItem=function(){throw Error("Operation not supported");};c.prototype.removeAt=function(){throw Error("Operation not supported");};c.prototype.removeRange=function(){throw Error("Operation not supported");};c.prototype.clear=function(){throw Error("Operation not supported");};c.prototype.set=function(){throw Error("Operation not supported");};c.prototype.sync=function(){throw Error("Operation not supported");
};c.prototype.equals=function(){throw Error("Operation not supported");};return c}(ObservableCollection);f.ObservableCollectionAggregator=i})(f.ui||(f.ui={}))})(e.framework||(e.framework={}))})(geocortex||(geocortex={}));
(function(e){(function(e){(function(e){(function(f){var j=function(c){function b(){c.apply(this,arguments)}__extends(b,c);b.prototype.handleClickTab=function(a,b,g){(a=g.view)&&this.app.viewManager.activateView(a)};return b}(e.ViewBase);f.ButtonTabStripView=j})(e.ViewContainer||(e.ViewContainer={}))})(e.ui||(e.ui={}))})(e.framework||(e.framework={}))})(geocortex||(geocortex={}));
(function(e){(function(e){(function(e){(function(e){var f=function(){return function(c,b,a,d){this.containerViewId=c;this.viewId=b;this.xButtonClicked=a;this.backButtonClicked=d}}();e.ViewContainerViewClosedEventArgs=f})(e.ViewContainer||(e.ViewContainer={}))})(e.ui||(e.ui={}))})(e.framework||(e.framework={}))})(geocortex||(geocortex={}));
(function(e){(function(f){(function(f){(function(i){var j=function(c){function b(a,b){c.call(this,a,b);this._active=this._hasDiscoveredRegions=false;this._keyDownEventToken=null;this._activatingForViewInContainer=false;this.headerInsertDomElement=new Observable(null);this.footerInsertDomElement=new Observable(null);this.scrollContainerTop=new Observable(0);this.scrollContainerBottom=new Observable(0);this.app.eventRegistry.event("ViewActivatedInContainerEvent").subscribe(this,function(a){this._activatingForViewInContainer=
false;var b=null;if(this.viewModel&&(b=this.viewModel.getDescriptorForActiveView(a))){this._activatingForViewInContainer=true;this.regionName&&this.app.viewManager.activateView(this);var d=b.scrollTop===void 0?0:b.scrollTop;setTimeout(dojo.hitch(this,function(){dojo.style(this.scrollRegionElement,"scrollTop",d);this.scrollRegionElement.scrollTop=d}),0);this.delayedResize()}});this.app.eventRegistry.event("RegionActivatedEvent").subscribe(this,this.handleRegionActivatedEvent);this.app.eventRegistry.event("RegionDeactivatedEvent").subscribe(this,
this.handleRegionDeactivatedEvent);this.app.eventRegistry.event("ViewDimensionsChangedEvent").subscribe(this,this.resize);this.app.eventRegistry.event("SiteInitializedEvent").subscribe(this,this.delayedResize)}__extends(b,c);b.prototype.attach=function(a){c.prototype.attach.call(this,a);this.title.sync(this.viewModel.viewTitle);if(this.root&&!this._hasDiscoveredRegions)this._hasDiscoveredRegions=true,this.app.viewManager.discoverRegions(this.root,this);this.headerInsertDomElement.sync(this.viewModel.headerInsertDomElement);
this.footerInsertDomElement.sync(this.viewModel.footerInsertDomElement);this.resize()};b.prototype.resize=function(){if(this.headerElement&&this.scrollRegionElement&&this.containerElement){var a=this.footerElement,b=this.scrollRegionElement,g=dojo.position(this.headerElement),a=dojo.position(a),g=g?g.h:0,a=a?a.h:0;dojo.style(b,"position")!=="relative"&&dojo.style(b,"top",g+"px");dojo.style(b,"bottom",a+"px")}};b.prototype.delayedResize=function(){var a=this;setTimeout(function(){a.resize.apply(a,
[])},1)};b.prototype.getZerothView=function(){for(var a=0;a<this.viewModel.viewDescriptors.getLength();++a){var b=this.viewModel.viewDescriptors.getAt(a);if(this.viewModel.getViewPriority(b.view.id)===0)return b.view}return null};b.prototype.activated=function(){c.prototype.activated.call(this);if(!this._active&&this.viewModel&&!this._activatingForViewInContainer){this._activatingForViewInContainer=false;this._active=true;var a=this.getZerothView();if(a&&!a.isActive)this.app.viewManager.activateView(a),
this._active=true;else var b=this.viewModel.viewDescriptors.bind(this,function(a){if((a=a.sender.getAt(0))&&this.viewModel.getViewPriority(a.view.id)===0)a.view.isActive||this.app.viewManager.activateView(a.view),this.viewModel.viewDescriptors.unbind(b)})}this.viewModel&&this.viewModel.showOrHideCloseButtons();if(this.viewModel&&this.viewModel.closeOnEscape)this._keyDownEventToken=dojo.connect(document,"keydown",this,this._documentKeyDown);this.delayedResize()};b.prototype.deactivated=function(){c.prototype.deactivated.call(this);
this._activatingForViewInContainer=false;if(this._keyDownEventToken)dojo.disconnect(this._keyDownEventToken),this._keyDownEventToken=null};b.prototype.activateContainer=function(){this._active=true;this.regionName&&this.app.viewManager.activateView(this)};b.prototype.deactivateContainer=function(){this._active=false;this.app.viewManager.deactivateView(this)};b.prototype._documentKeyDown=function(a){if(a.keyCode===27&&this.viewModel)a=this.viewModel.currentView,this._closeCurrentView(this.viewModel),
this._broadcastClosedEvent(a,true,false)};b.prototype.handleScrollChange=function(a,b,c){c.getDescriptorForActiveView(c.currentView).scrollTop=b.scrollTop};b.prototype.handleRegionActivatedEvent=function(a){this.viewModel&&a.name===this.viewModel.regionName.get()&&this.activateContainer()};b.prototype.handleRegionDeactivatedEvent=function(a){this.viewModel&&a.name===this.viewModel.regionName.get()&&this.deactivateContainer()};b.prototype.handleClickBack=function(a,b,c){a=c.currentView;this._closeCurrentView(c);
this._broadcastClosedEvent(a,false,true)};b.prototype.handleClickClose=function(a,b,c){a=c.currentView;this._closeCurrentView(c);this._broadcastClosedEvent(a,true,false)};b.prototype.handleClickTab=function(a,b,c){(a=c.view)&&this.app.commandRegistry.command("ActivateView").execute(a.id)};b.prototype.handleClickCloseTab=function(a,b,c){(a=c.view)&&this.app.viewManager.destroyView(a)};b.prototype._closeCurrentView=function(a){a.closeCurrentView()};b.prototype._broadcastClosedEvent=function(a,b,c){a=
new e.framework.ui.ViewContainer.ViewContainerViewClosedEventArgs(this.id,a.id,b,c);this.app.eventRegistry.event("ViewContainerViewClosedEvent").publish(a)};return b}(f.ViewBase);i.ViewContainerView=j})(f.ViewContainer||(f.ViewContainer={}))})(f.ui||(f.ui={}))})(e.framework||(e.framework={}))})(geocortex||(geocortex={}));
(function(e){(function(f){(function(f){(function(i){var j=function(c){function b(a,b){c.call(this,a,b);this.regionName=new Observable("");this.headerIsVisible=new Observable(true);this.titleBarIsVisible=new Observable(true);this.hasCustomHeaderComponent=new Observable(false);this.hasCustomFooterComponent=new Observable(false);this.showingBackButton=new Observable(true);this.showBusyIndicator=new Observable(false);this.showHostedViews=new Observable(false);this.showingXButton=new Observable(true);
this.containerTitle=new Observable("");this.viewTitle=new Observable("");this.fullTitle=new Observable("");this.viewDescriptors=new ObservableCollection([]);this.activeViewDescriptors=new ObservableCollection([]);this.headerInsertDomElement=new Observable(null);this.footerInsertDomElement=new Observable(null);this._activeViews={};this._insertedViews=[];this._ordering={};this._showBackButtonAsX=this._showBackButton=this._backButtonOnRootView=true;this._showHeaderForStandaloneViews=this._originalHeaderIsVisibleSetting=
false;this._fullTitleFormatString="{0} - {1}";this._defaultViewIconUri=null;var g=this.app.viewManager.getExistingRegionByName(this.regionName.get());if(g)for(var e=0;e<g.views.length;++e){var f=g.views[e];this._addOrderedView({view:f,iconUri:f.iconUri.get()?f.iconUri:new Observable(this._defaultViewIconUri),title:f.title,isBusy:f.isBusy,isActive:new Observable(false),cssClass:new Observable("tab-inactive")})}this.app.eventRegistry.event("ViewHostedEvent").subscribe(this,this.handleViewHosted);this.app.eventRegistry.event("ViewUnhostedEvent").subscribe(this,
this.handleViewUnhosted);this.app.eventRegistry.event("ViewActivatedEvent").subscribe(this,this.handleViewActivatedEvent);this.app.eventRegistry.event("ViewDeactivatedEvent").subscribe(this,this.handleViewDeactivatedEvent)}__extends(b,c);b.prototype.initialize=function(a){this.regionName.set(a.containerRegionName);this.containerTitle.set(a.containerTitle||null);this._defaultViewIconUri=a.defaultViewIcon||null;this._originalHeaderIsVisibleSetting=a.headerIsVisible!==null&&a.headerIsVisible!==void 0?
!!a.headerIsVisible:true;this._showHeaderForStandaloneViews=!!a.showHeaderForStandaloneViews;this.headerIsVisible.set(this._originalHeaderIsVisibleSetting);this.showHostedViews.set(!!a.showHostedViews);this._ordering=a.ordering||{};this._backButtonOnRootView=a.backButtonOnRootView;this._showBackButtonAsX=a.showBackButtonAsX;this.closeOnEscape=!!a.closeOnEscape;var b=function(b,d){if(a["{0}InsertMarkup".format(b)])try{var c=this.app.viewManager.createView({markup:a["{0}InsertMarkup".format(b)],type:a["{0}InsertType".format(b)]});
c.attach(this);this._insertedViews.push(c);d.set(c.root)}catch(e){this.app.trace.error("Could not create view {0} container insert: {1}".format(b,e.toString()))}};b.apply(this,["header",this.headerInsertDomElement]);b.apply(this,["footer",this.footerInsertDomElement])};b.prototype.getDescriptorForView=function(a){for(var b=0;b<this.viewDescriptors.getLength();++b){var c=this.viewDescriptors.getAt(b);if(c.view===a)return c}return null};b.prototype.getDescriptorForActiveView=function(a){for(var b=0;b<
this.activeViewDescriptors.getLength();++b){var c=this.activeViewDescriptors.getAt(b);if(c.view===a)return c}return null};b.prototype.handleViewHosted=function(a){var b=a.region,a=a.view;b&&b.name===this.regionName.get()&&!this.getDescriptorForView(a)&&(b={view:a,iconUri:a.iconUri.get()?a.iconUri:new Observable(this._defaultViewIconUri),title:a.title,isBusy:a.isBusy,isActive:new Observable(false),cssClass:new Observable("tab-inactive")},this._addOrderedView(b),this.showHostedViews.get()&&(this.getDescriptorForActiveView(a)||
this.activeViewDescriptors.addItem(b)))};b.prototype.handleViewUnhosted=function(a){var b=a.region,a=a.view;if(b&&b.name===this.regionName.get()&&(b=this.getDescriptorForView(a)))this.viewDescriptors.removeItem(b),this.showHostedViews.get()||this.activeViewDescriptors.removeItem(b)};b.prototype.handleViewActivatedEvent=function(a){var b=this.app.viewManager.getRegionForViewId(a.id);b&&b.name===this.regionName.get()&&(b=this.getDescriptorForView(a),b||(b={view:a,iconUri:a.iconUri.get()?a.iconUri:new Observable(this._defaultViewIconUri),
title:a.title,isBusy:a.isBusy,isActive:new Observable(false),cssClass:new Observable("tab-inactive")},this._addOrderedView(b)),this._activeViews[a.id]=true,this.app.trace.debug("--- Activated view {0}".format(a.id)),this.activateViewInContainer(a))};b.prototype.handleViewDeactivatedEvent=function(a){var b=this.app.viewManager.getRegionForViewId(a.id);b&&b.name===this.regionName.get()&&(this._activeViews[a.id]=false,(b=this.getDescriptorForView(a))&&!this.showHostedViews.get()&&this.activeViewDescriptors.removeItem(b),
this.app.trace.debug("--- Deactivated view {0}".format(a.id)),this.deactivateViewInContainer(a))};b.prototype.activateViewInContainer=function(a){this.deactivateViews();this.currentView=a;var b=this.getDescriptorForView(a);b?(b.isActive.set(true),b.cssClass.set("tab-active")):a.isManaged&&(b={view:a,iconUri:a.iconUri.get()?a.iconUri:new Observable(this._defaultViewIconUri),title:a.title,isBusy:a.isBusy,isActive:new Observable(true),cssClass:new Observable("tab-active")},this._addOrderedView(b));this.getDescriptorForActiveView(a)||
this.activeViewDescriptors.addItem(b);this.app.eventRegistry.event("ViewActivatedInContainerEvent").publish(a);this._showHeaderForStandaloneViews&&!(a instanceof e.framework.ui.ViewContainer.ViewContainerView)?this.headerIsVisible.set(true):this.headerIsVisible.set(this._originalHeaderIsVisibleSetting);this.showOrHideCloseButtons();this.viewTitle.sync(a.title);this.showBusyIndicator.sync(a.isBusy)};b.prototype.showOrHideCloseButtons=function(){var a=this.viewDescriptors.getAt(0);a&&(this.currentView===
a.view?this._backButtonOnRootView?(this.showingXButton.set(this._showBackButtonAsX),this.showingBackButton.set(!this._showBackButtonAsX)):(this.showingBackButton.set(false),this.showingXButton.set(false)):(this.showingXButton.set(this._showBackButtonAsX),this.showingBackButton.set(!this._showBackButtonAsX)))};b.prototype.deactivateViewInContainer=function(a){if(a=this.getDescriptorForView(a))a.isActive.set(false),a.cssClass.set("tab-inactive"),this.showHostedViews.get()||this.activeViewDescriptors.removeItem(a);
this.showOrHideCloseButtons()};b.prototype.closeCurrentView=function(){var a=this.getDescriptorForView(this.currentView);a&&!this.showHostedViews.get()&&this.activeViewDescriptors.removeItem(a);this.deactivateCurrentView()};b.prototype.deactivateCurrentView=function(){this.currentView&&this.app.viewManager.deactivateView(this.currentView)};b.prototype.deactivateViews=function(){for(var a=0;a<this.viewDescriptors.getLength();++a){var b=this.viewDescriptors.getAt(a);b.isActive.set(false);b.cssClass.set("tab-inactive")}};
b.prototype.getViewPriority=function(a){return this._ordering.hasOwnProperty(a)?parseInt(this._ordering[a]):null};b.prototype._addOrderedView=function(a){var b=a.view,c=this.getDescriptorForActiveView(b);if(this._ordering){var e=b.id;if(e)if(e=this.getViewPriority(e),e===null||e===void 0)this.viewDescriptors.addItem(a),b.isActive&&!c&&this.activeViewDescriptors.addItem(a);else{for(var f=false,i=0;i<this.viewDescriptors.getLength();++i){var j=this.getViewPriority(this.viewDescriptors.getAt(i).view.id);
if(j===null||e<=j){f=true;this.viewDescriptors.insertItem(i,a);b.isActive&&this.activeViewDescriptors.insertItem(i,a);break}}f||(this.viewDescriptors.addItem(a),b.isActive&&!c&&this.activeViewDescriptors.addItem(a))}else this.viewDescriptors.addItem(a),b.isActive&&!c&&this.activeViewDescriptors.addItem(a)}else this.viewDescriptors.addItem(a),b.isActive&&!c&&this.activeViewDescriptors.addItem(a)};b.prototype.dispose=function(){for(var a=0;a<this._insertedViews.length;a++)this.app.viewManager.destroyView(this._insertedViews[a]);
this._insertedViews.length=0};return b}(f.ViewModelBase);i.ViewContainerViewModel=j})(f.ViewContainer||(f.ViewContainer={}))})(f.ui||(f.ui={}))})(e.framework||(e.framework={}))})(geocortex||(geocortex={}));geocortex.resourceManager.register("Framework.UI","inv","Framework.UI/geocortex/framework/ui/SplashScreen/SplashScreenView.html","html","PGRpdiBjbGFzcz0ic3BsYXNoLXNjcmVlbiI+PC9kaXY+IA==");
geocortex.resourceManager.register("Framework.UI","inv","Framework.UI/geocortex/framework/ui/ViewContainer/ButtonTabStripView.html","html","DQo8ZGl2IGNsYXNzPSJidXR0b24tdGFiLXN0cmlwIj4gPHVsIGRhdGEtYmluZGluZz0ie0Bzb3VyY2U6IGFjdGl2ZVZpZXdEZXNjcmlwdG9yc30iPiA8bGkgZGF0YS1iaW5kaW5nPSJ7QHRlbXBsYXRlLWZvcjogYWN0aXZlVmlld0Rlc2NyaXB0b3JzfXtAZXZlbnQtb25jbGljazogaGFuZGxlQ2xpY2tUYWJ9e2NsYXNzTmFtZTogY3NzQ2xhc3N9Ij4gPGltZyBjbGFzcz0idGFiLXN0cmlwLWljb24iIGRhdGEtYmluZGluZz0ie3NyYzogaWNvblVyaX17YWx0OiB0aXRsZX17dGl0bGU6IHRpdGxlfXtAdmlzaWJsZTogaWNvblVyaX0iLz4gPC9saT4gPC91bD4gPC9kaXY+IA==");
geocortex.resourceManager.register("Framework.UI","inv","Framework.UI/geocortex/framework/ui/ViewContainer/ViewContainerView.html","html","PGRpdiBjbGFzcz0idmlldy1jb250YWluZXItdmlldyIgZGF0YS1iaW5kaW5nPSJ7QHZhcjogY29udGFpbmVyRWxlbWVudH0iPiAgPGRpdiBjbGFzcz0icGFuZWwtaGVhZGVyIiBkYXRhLWJpbmRpbmc9IntAdmlzaWJsZTogaGVhZGVySXNWaXNpYmxlfXtAdmFyOiBoZWFkZXJFbGVtZW50fSI+IDxkaXYgZGF0YS1iaW5kaW5nPSJ7QHZpc2libGU6IHRpdGxlQmFySXNWaXNpYmxlfSI+ICA8YSBjbGFzcz0icGFuZWwtaGVhZGVyLWJ1dHRvbiByaWdodCBjbG9zZS0xNiIgaHJlZj0iamF2YXNjcmlwdDp2b2lkKDApIiBkYXRhLWJpbmRpbmc9IntAdmlzaWJsZTogc2hvd2luZ1hCdXR0b259e0BldmVudC1vbmNsaWNrOiBoYW5kbGVDbGlja0Nsb3NlfSI+PC9hPiAgPGEgY2xhc3M9InBhbmVsLWhlYWRlci1idXR0b24gbGVmdCBiYWNrLTE2IiBocmVmPSJqYXZhc2NyaXB0OnZvaWQoMCkiIGRhdGEtYmluZGluZz0ie0B2aXNpYmxlOiBzaG93aW5nQmFja0J1dHRvbn17QGV2ZW50LWNsaWNrOiBoYW5kbGVDbGlja0JhY2t9Ij48L2E+IDxoMiBjbGFzcz0icGFuZWwtdGl0bGUiPiA8aW1nIHNyYz0iUmVzb3VyY2VzL0ltYWdlcy9sb2FkZXItc21hbGwuZ2lmIiBkYXRhLWJpbmRpbmc9IntAdmlzaWJsZTogc2hvd0J1c3lJbmRpY2F0b3J9IiAvPiA8c3BhbiBkYXRhLWJpbmRpbmc9IntAdGV4dDogY29udGFpbmVyVGl0bGV9e0B2aXNpYmxlOiBjb250YWluZXJUaXRsZX0iPjwvc3Bhbj4gPHNwYW4gZGF0YS1iaW5kaW5nPSJ7QHZpc2libGU6IGNvbnRhaW5lclRpdGxlfSI+Jm5ic3A7LSZuYnNwOzwvc3Bhbj4gPHNwYW4gZGF0YS1iaW5kaW5nPSJ7QHRleHQ6IHZpZXdUaXRsZX17QHZpc2libGU6IHZpZXdUaXRsZX0iPjwvc3Bhbj4gPC9oMj4gPC9kaXY+IDxkaXYgZGF0YS1iaW5kaW5nPSJ7QGRvbTogaGVhZGVySW5zZXJ0RG9tRWxlbWVudH0iPjwvZGl2PiA8L2Rpdj4gICAgPGRpdiBjbGFzcz0icGFuZWwtc2Nyb2xsLWNvbnRhaW5lciIgZGF0YS1iaW5kaW5nPSJ7ZGF0YS1yZWdpb24tbmFtZTogcmVnaW9uTmFtZX17QHZhcjogc2Nyb2xsUmVnaW9uRWxlbWVudH17QGV2ZW50LW9uc2Nyb2xsOiBoYW5kbGVTY3JvbGxDaGFuZ2V9IiBkYXRhLXJlZ2lvbi1hZGFwdGVyPSJnZW9jb3J0ZXguZnJhbWV3b3JrLnVpLk11bHRpRGl2UmVnaW9uQWRhcHRlciI+PC9kaXY+ICAgPGRpdiBjbGFzcz0icGFuZWwtZm9vdGVyIiBkYXRhLWJpbmRpbmc9IntAdmFyOiBmb290ZXJFbGVtZW50fXtAdmlzaWJsZTogZm9vdGVySW5zZXJ0RG9tRWxlbWVudH0iIHN0eWxlPSJwb3NpdGlvbjogYWJzb2x1dGUiPiA8ZGl2IGNsYXNzPSJwYW5lbC1mb290ZXItaW5uZXIiIGRhdGEtYmluZGluZz0ie0Bkb206IGZvb3Rlckluc2VydERvbUVsZW1lbnR9Ij48L2Rpdj4gPC9kaXY+ICA8L2Rpdj4g");
geocortex.framework.notifyLibraryDownload("Framework.UI");
